### ISSUE TITLE
file transfer ERROR

### ISSUE THREAD

**Issue by kairos03** [kairos96/Dron-File-Transfer#1]
when file is transfering, the last buffer are not saved

**Comment by goldragoon** [comment]
Actually It really works well...... in the local.
Does the problem occurs in remote network environment?

**Comment by kairos03** [comment]
a really? works well in local? 
humm....

**Comment by kairos03** [comment]
in the file name sending prosess, file name can be char[50]
but wifi envirment filename is more then real filename so some file data stored with filename 
so i fix that fixed file name 23byte
